apiVersion: 1


datasources:
- name: Postgres
type: postgres
access: proxy
url: db:5432
database: ${POSTGRES_DB}
user: ${POSTGRES_USER}
secureJsonData:
password: ${POSTGRES_PASSWORD}
jsonData:
sslmode: "disable"